#!/usr/bin/env node

// Shim to run spotify_list.ts via ts-node
require('ts-node').register({});

(async () => {
  try {
    await import('../src/spotify_list.ts');
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
})();
